esphome:
  name: "ahub-filter-roller-water-level"
  friendly_name: "ahub-filter-roller-water-level"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pBF6hsDmXdI/0W/0yY+HE8GQMx/PxxXpGIEERwS/Xro="

ota:
  password: "a9bd8e6a0e47feb411927302c1fce1e2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ahub-Filter-Roller"
    password: "0oL9kWOSUfkO"

captive_portal:

web_server:
  port: 80

mqtt:
  broker: 192.168.1.11
  username: !secret mqtt_username
  password: !secret mqtt_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
    name: "Water Level"
    id: filter_roller_water_level_sensor
    on_press:
      - mqtt.publish:
          topic: ahub/sump/filter_roller_level/out
          payload: "0"
    on_release:
      - mqtt.publish:
          topic: ahub/sump/filter_roller_level/out
          payload: "1"

interval:
  - interval: 300s
    then:
      - mqtt.publish:
          topic: ahub/sump/filter_roller_level/out
          payload: !lambda |-
            return id(filter_roller_water_level_sensor).state ? "0" : "1";