substitutions:
  devicename: "ahub-sump-dht"

esphome:
  name: $devicename
  friendly_name: $devicename

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: "yzcCRwfGLaKM+l5YJWos8xe4sBb1/y0ed8aJCVEifoc="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $devicename
    password: "012345678"

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: $devicename Version
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    bssid:
      name: $devicename BSSID

sensor:
  - platform: uptime
    name: $devicename uptime
  - platform: wifi_signal
    name: $devicename wifi signal
    update_interval: 60s
  - platform: dht
    pin: GPIO3
    model: AM2302
    temperature:
      name: "${devicename}-temperature"
    humidity:
      name: "${devicename}-humidity"
    update_interval: 60s